spring:
  profiles.active: debug
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
---
spring:
  profiles: debug

logging:
  file.name: ./logs/debug.log
  level:
    root: info
    im.silen.vueboot: trace
---
spring:
  profiles: build
server.servlet.context-path: /api

logging.file.name: ./logs/build.log