spring:
  profiles.active: dev
  jackson:
    date-format: yyyy--MM-dd HH?mm?ss
    time-zone: GMT+8

logging.level:
  root: info
  im.silen.vueboot.mapper: trace
---
spring:
  profiles: dev

---
spring:
  profiles: prod